spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hexagonal_db?useSSL=false&serverTimezone=UTC
    username: root
    password: qaqawesd12@
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  thymeleaf:
    cache: false

server:
  port: 8080

app:
  security:
    default-admin-username: admin
    default-admin-password: adminpass
